// Generated by tools/pokemon/import-set-vectors.mjs. Do not edit.
export const POKEMON_SET_VECTOR_ICON_URLS: Readonly<Record<string, string>> = Object.freeze({
  base2:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/base2.89bacb80a2ace093.svg',
  basep:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/basep.9917d68cf99f050a.svg',
  base3:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/base3.b3c5281ec9a5b36c.svg',
  base4:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/base4.29ede0a44e243b84.svg',
  base5:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/base5.f4e789a333cce9d2.svg',
  gym1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/gym1.c4c08adef035aca1.svg',
  gym2: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/gym2.66438d5ec4f55231.svg',
  neo1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/neo1.e80e547f919a3131.svg',
  neo2: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/neo2.922d8f3fe9bf5072.svg',
  si1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/si1.e3614138fdf9aad0.svg',
  neo3: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/neo3.ec6d69e95878eb58.svg',
  neo4: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/neo4.77d80d4d9262f46c.svg',
  lc: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/lc.60cda76bb0bc146b.svg',
  ecard1:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ecard1.beacc6f8cb48db0f.svg',
  bog: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bog.1d665295927c5c53.svg',
  ecard2:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ecard2.aae0436e2e593f85.svg',
  ecard3:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ecard3.2d62fb008f19d868.svg',
  ex1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex1.fad8cd36c6a40bba.svg',
  ex2: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex2.1863daec89a7579a.svg',
  np: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/np.9917d68cf99f050a.svg',
  ex3: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex3.82451b54044f3298.svg',
  ex4: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex4.108f3efc7ff86a9a.svg',
  ex5: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex5.2474fd298cf0af55.svg',
  'tk-ex-latia':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-ex-latia.e160c628160c6958.svg',
  'tk-ex-latio':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-ex-latio.08d03c4e480d68dc.svg',
  pop1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pop1.50da150f0511ea9d.svg',
  ex6: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex6.4b6a2661f343b5a3.svg',
  ex7: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex7.c5866c5dc7b64da9.svg',
  ex8: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex8.4802e07416d1cc33.svg',
  ex9: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex9.ea946c65c9ca6e22.svg',
  pop2: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pop2.f6b8352f8a695ba8.svg',
  ex10: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex10.2e060745a96a7c77.svg',
  exu: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/exu.2e060745a96a7c77.svg',
  ex11: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex11.69ec6153f9bd8909.svg',
  ex12: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex12.04c1e1a19b3da1dd.svg',
  'tk-ex-m':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-ex-m.dd6d5c3c997e0cb8.svg',
  'tk-ex-p':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-ex-p.59e84bded5bb3356.svg',
  pop3: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pop3.6337ec18d71aca02.svg',
  ex13: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex13.938e452da13ad730.svg',
  pop4: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pop4.cbbf30a9e29fe6b2.svg',
  ex14: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex14.b31068a5bd7e5040.svg',
  ex15: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex15.d104977d93b023f8.svg',
  ex16: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ex16.00e9831ba4f9ec37.svg',
  pop5: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pop5.f703e42d0f5c1969.svg',
  dpp: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/dpp.9917d68cf99f050a.svg',
  dp1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/dp1.1ff44950dd8f1be1.svg',
  dp2: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/dp2.476748d1eec7fd11.svg',
  'tk-dp-l':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-dp-l.c510b97d09bcfe2e.svg',
  'tk-dp-m':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-dp-m.a6878cbc3b65eead.svg',
  pop6: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pop6.2b2a005c9241bdb8.svg',
  dp3: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/dp3.56eacc456f7b4c94.svg',
  dp4: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/dp4.5a8cbf02be0d8f98.svg',
  pop7: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pop7.95cb51a224e87e4c.svg',
  dp5: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/dp5.4e4997a63af891e3.svg',
  dp6: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/dp6.38b7d61a24025ec5.svg',
  pop8: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pop8.af6451f5f1988ace.svg',
  dp7: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/dp7.c0da72fd4c6807b3.svg',
  pl1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pl1.a93f7d8a0310a684.svg',
  pop9: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pop9.b213a963c73200a6.svg',
  pl2: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pl2.adbd6e7d595ef645.svg',
  pl3: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pl3.c81f739d8b9ac327.svg',
  pl4: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/pl4.f2944360cc9b972c.svg',
  ru1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/ru1.bf67fb9e05b98018.svg',
  hgssp:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/hgssp.9917d68cf99f050a.svg',
  'tk-hs-r':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-hs-r.28cfef04c436a1c9.svg',
  'tk-hs-g':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-hs-g.8526e02cdc403b0b.svg',
  hgss2:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/hgss2.4069045307ac3a9c.svg',
  hgss3:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/hgss3.610ff76ca86e7c62.svg',
  hgss4:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/hgss4.787b812e61b3c480.svg',
  col1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/col1.d8c6f151d18fe47d.svg',
  bw1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bw1.188703ba5eefa5de.svg',
  bwp: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bwp.9917d68cf99f050a.svg',
  '2011bw':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/2011bw.90af672312ed813d.svg',
  bw2: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bw2.d09dd5a44a4e449e.svg',
  'tk-bw-z':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-bw-z.a15415acdf2a65e2.svg',
  'tk-bw-e':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-bw-e.55ab11afaa010956.svg',
  bw3: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bw3.b3065feaa0ed905c.svg',
  bw4: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bw4.2b863e12c3f7a359.svg',
  bw5: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bw5.3efc144d14008d8e.svg',
  '2012bw':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/2012bw.eab3a1965f0e3c85.svg',
  bw6: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bw6.3959f7d64fe28477.svg',
  dv1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/dv1.0a74f9fffc12adc0.svg',
  bw7: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bw7.cb2b0dac0bcf9dff.svg',
  bw8: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bw8.58d7d4c5dd796231.svg',
  bw9: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bw9.bda94db538a700e7.svg',
  bw10: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bw10.42b564034e8a2c83.svg',
  xyp: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xyp.9917d68cf99f050a.svg',
  bw11: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/bw11.4bca50ffae3c17f1.svg',
  xy0: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy0.73f5a9a8b68b55d2.svg',
  xy1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy1.574178ee509dfe11.svg',
  'tk-xy-sy':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-xy-sy.b62e4d41fecca6ba.svg',
  'tk-xy-n':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-xy-n.a688d4ed45278aab.svg',
  xy2: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy2.e8effb281e1b2a62.svg',
  '2014xy':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/2014xy.c065304cad800510.svg',
  xy3: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy3.320683424c7299c1.svg',
  'tk-xy-b':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-xy-b.254423a3d4198415.svg',
  'tk-xy-w':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-xy-w.d2025584546ab866.svg',
  xy4: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy4.898e3137bb38ef1d.svg',
  xy5: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy5.1a6d6a6de3e099fc.svg',
  dc1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/dc1.5bd3047274ed9976.svg',
  'tk-xy-latia':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-xy-latia.e5e66d29ae691a3f.svg',
  'tk-xy-latio':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-xy-latio.3fa92fd314b4faa9.svg',
  xy6: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy6.a3da591957844486.svg',
  xy7: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy7.ccf35c9f5de0bc04.svg',
  xy8: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy8.592284c1f77b59e7.svg',
  '2015xy':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/2015xy.6ffa1a53fad6e394.svg',
  xy9: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy9.f303fa5ce840206b.svg',
  g1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/g1.121f527c1ab41c01.svg',
  'tk-xy-su':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-xy-su.8a9eaaed611112fd.svg',
  'tk-xy-p':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-xy-p.0b3165037c4bdd95.svg',
  xy10: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy10.14da95e59d24db9c.svg',
  xy11: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy11.1f1390c1d402019b.svg',
  '2016xy':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/2016xy.0fe6035f9ec7b714.svg',
  xy12: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/xy12.a15c9c7dce1ab97f.svg',
  smp: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/smp.9917d68cf99f050a.svg',
  sm1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm1.c9372b1fc045482e.svg',
  'tk-sm-r':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-sm-r.02a807f0273fd879.svg',
  'tk-sm-l':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/tk-sm-l.744d25a2de160445.svg',
  sm2: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm2.d04b4119f3f85578.svg',
  '2017sm':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/2017sm.494b801e45ccb7e8.svg',
  sm3: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm3.d50c45296d376e5a.svg',
  'sm3.5':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm3.5.a6df98d91cad8b3e.svg',
  sm4: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm4.1cb017c7c6a4f6ee.svg',
  sm5: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm5.653b83da256679a7.svg',
  sm6: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm6.1be377b6deee90c2.svg',
  sm7: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm7.71af1914370739d0.svg',
  'sm7.5':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm7.5.6797709c560cae4d.svg',
  '2018sm':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/2018sm.362d44d015a83f2f.svg',
  sm8: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm8.9f5adadedf9ada31.svg',
  sm9: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm9.239534ca6a469d3b.svg',
  det1: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/det1.98b9aa69ae0bea82.svg',
  sm10: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm10.34cd2ed610606a10.svg',
  sm11: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm11.c6a833459bf42466.svg',
  sma: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sma.246f4f78cbb3b591.svg',
  sm115:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm115.246f4f78cbb3b591.svg',
  '2019sm':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/2019sm.077fb891d0f6a8fc.svg',
  sm12: 'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/sm12.a428566cd5eb3d99.svg',
  swshp:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swshp.9917d68cf99f050a.svg',
  swsh1:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh1.9e8493051258b16a.svg',
  swsh2:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh2.b11867a3d430d5d8.svg',
  swsh3:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh3.0277d8d69c58e572.svg',
  fut2020:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/fut2020.25351c01af4de9b3.svg',
  'swsh3.5':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh3.5.6a49d44a308cfa0b.svg',
  swsh4:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh4.bf3a4d3d871b6ef1.svg',
  '2021swsh':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/2021swsh.de80eb937c6d698f.svg',
  'swsh4.5sv':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh4.5sv.3123752422cca000.svg',
  'swsh4.5':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh4.5.3123752422cca000.svg',
  swsh5:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh5.09d7f90602254a4a.svg',
  swsh6:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh6.43947113c80fd7b1.svg',
  swsh7:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh7.221dce62dbc174bf.svg',
  cel25cc:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/cel25cc.e2b4bed0584c98ee.svg',
  cel25:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/cel25.e2b4bed0584c98ee.svg',
  swsh8:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh8.685fec51a9431566.svg',
  swsh9:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh9.c08926744a1497c2.svg',
  'swsh9.5tg':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh9.5tg.c08926744a1497c2.svg',
  'swsh10.5tg':
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh10.5tg.afd25c7f4758e373.svg',
  swsh10:
    'https://assets.tcger.ahmadjalil.com/catalogs/pokemon-set-symbols/swsh10.afd25c7f4758e373.svg',
});
