version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tcg_collection}
      POSTGRES_USER: ${POSTGRES_USER:-tcguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tcgpassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tcg-net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - tcg-net

  scryfall-bulk:
    build:
      context: ..
      dockerfile: services/scryfall-bulk/Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      SCRYFALL_BULK_TYPE: ${SCRYFALL_BULK_TYPE:-oracle_cards}
      SCRYFALL_BULK_REFRESH_MS: ${SCRYFALL_BULK_REFRESH_MS:-43200000}
      SCRYFALL_BULK_MAX_RESULTS: ${SCRYFALL_BULK_MAX_RESULTS:-50}
      PORT: 4010
    volumes:
      - scryfall_bulk_data:/data
    profiles:
      - bulk
    networks:
      - tcg-net

  ygo-cache:
    build:
      context: ..
      dockerfile: services/ygo-cache/Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      YGO_SOURCE_BASE_URL: ${YGO_SOURCE_BASE_URL:-https://db.ygoprodeck.com/api/v7}
      YGO_CACHE_REFRESH_MS: ${YGO_CACHE_REFRESH_MS:-43200000}
      YGO_CACHE_PAGE_SIZE: ${YGO_CACHE_PAGE_SIZE:-20}
      YGO_CACHE_MAX_PAGE_SIZE: ${YGO_CACHE_MAX_PAGE_SIZE:-200}
      PORT: 4020
    volumes:
      - ygo_cache_data:/data
    profiles:
      - bulk
    networks:
      - tcg-net

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
      target: production
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT:-3000}
      DATABASE_URL: postgresql://${POSTGRES_USER:-tcguser}:${POSTGRES_PASSWORD:-tcgpassword}@postgres:5432/${POSTGRES_DB:-tcg_collection}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:?err}
      POKEMON_TCG_API_KEY: ${POKEMON_TCG_API_KEY:-}
      SCRYFALL_API_BASE_URL: ${SCRYFALL_API_BASE_URL:-https://api.scryfall.com}
      YGO_API_BASE_URL: ${YGO_API_BASE_URL:-https://db.ygoprodeck.com/api/v7}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - tcg-net

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
      target: production
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://localhost:3000}
    ports:
      - "${FRONTEND_PORT:-3001}:3000"
    depends_on:
      backend:
        condition: service_started
    networks:
      - tcg-net

volumes:
  postgres_data:
  scryfall_bulk_data:
  ygo_cache_data:

networks:
  tcg-net:
    driver: bridge
