import Foundation

/// Checks the bundled scanner assets and reports what is present, missing, or
/// invalid. The recognition strategies deliberately disable themselves when
/// their assets are absent (a clean clone has no model/index — they are
/// gitignored build outputs), which historically made a broken scanner look
/// like "scanning silently does nothing". This surfaces the actual reason.
struct ScannerAssetDiagnostics {
    struct Item: Identifiable {
        let id = UUID()
        let name: String
        let isOK: Bool
        let detail: String
    }

    /// Bundled assets required by the on-device Pokémon embedding pipeline.
    /// These are generated by `bash scripts/ios-assets.sh build` (see
    /// Resources/ScanIndex/README.md) and are NOT tracked in git.
    private enum EmbeddingAsset {
        static let model = ("CardEmbeddings", "mlmodelc")
        static let vectors = ("CardsIndexVectors", "bin")
        static let metadata = ("CardsIndexMetadata", "json")
    }

    static func run(bundle: Bundle = .main) -> [Item] {
        var items: [Item] = []

        // CoreML embedding encoder (compiled from CardEmbeddings.mlpackage).
        if bundle.url(forResource: EmbeddingAsset.model.0, withExtension: EmbeddingAsset.model.1) != nil {
            items.append(Item(name: "Embedding model", isOK: true, detail: "CardEmbeddings.mlmodelc bundled"))
        } else {
            items.append(Item(
                name: "Embedding model",
                isOK: false,
                detail: "CardEmbeddings.mlmodelc missing — run scripts/ios-assets.sh build, then rebuild"
            ))
        }

        // Packed int8 embedding index.
        var vectorCount: Int?
        if let url = bundle.url(forResource: EmbeddingAsset.vectors.0, withExtension: EmbeddingAsset.vectors.1),
           let data = try? Data(contentsOf: url, options: .mappedIfSafe),
           data.count >= 8 {
            let count = Int(data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: 0, as: Int32.self).littleEndian })
            let dim = Int(data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: 4, as: Int32.self).littleEndian })
            if count > 0, dim > 0, data.count >= 8 + count * dim {
                vectorCount = count
                items.append(Item(name: "Embedding index", isOK: true, detail: "\(count) cards × \(dim)d"))
            } else {
                items.append(Item(name: "Embedding index", isOK: false, detail: "CardsIndexVectors.bin header invalid"))
            }
        } else {
            items.append(Item(
                name: "Embedding index",
                isOK: false,
                detail: "CardsIndexVectors.bin missing — run scripts/ios-assets.sh build, then rebuild"
            ))
        }

        // Index metadata (annIndex → card identity).
        if let url = bundle.url(forResource: EmbeddingAsset.metadata.0, withExtension: EmbeddingAsset.metadata.1),
           let data = try? Data(contentsOf: url, options: .mappedIfSafe),
           let entries = (try? JSONSerialization.jsonObject(with: data)) as? [[String: Any]] {
            if let vectorCount, entries.count != vectorCount {
                items.append(Item(
                    name: "Index metadata",
                    isOK: false,
                    detail: "\(entries.count) entries but index has \(vectorCount) vectors — regenerate both together"
                ))
            } else {
                items.append(Item(name: "Index metadata", isOK: true, detail: "\(entries.count) entries"))
            }
        } else {
            items.append(Item(
                name: "Index metadata",
                isOK: false,
                detail: "CardsIndexMetadata.json missing or unreadable — run scripts/ios-assets.sh build"
            ))
        }

        // Card-face rejection gate (tracked in git; missing only on broken bundles).
        if let gate = CardFaceRejectionGate.loadBundled(bundle: bundle) {
            items.append(Item(name: "Rejection gate", isOK: true, detail: "threshold \(gate.threshold)"))
        } else {
            items.append(Item(name: "Rejection gate", isOK: false, detail: "CardFaceGate.json missing — open-set gating disabled"))
        }

        // Artwork fingerprint databases (per game; Pokémon's ships in git).
        var fingerprintGames: [String] = []
        for mode in ScanMode.allCases {
            let resource = "artwork-fingerprints-\(mode.tcgGame.rawValue)-uint8"
            if let url = bundle.url(forResource: resource, withExtension: "json"),
               let size = try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize {
                fingerprintGames.append(mode.displayName)
                items.append(Item(
                    name: "Fingerprints — \(mode.displayName)",
                    isOK: true,
                    detail: String(format: "%.1f MB", Double(size) / 1_000_000)
                ))
            }
        }
        if let url = bundle.url(forResource: "artwork-fingerprints-uint8", withExtension: "json"),
           let size = try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize {
            fingerprintGames.append("legacy")
            items.append(Item(
                name: "Fingerprints — legacy file",
                isOK: true,
                detail: String(format: "%.1f MB (game declared inside the file)", Double(size) / 1_000_000)
            ))
        }
        if fingerprintGames.isEmpty {
            items.append(Item(
                name: "Artwork fingerprints",
                isOK: false,
                detail: "no artwork-fingerprints-<game>-uint8.json bundled — fingerprint fallback disabled"
            ))
        }

        // Magic perceptual hash database (tracked in git).
        if bundle.url(forResource: "MagicCardHashes", withExtension: "json") != nil {
            items.append(Item(name: "Magic hashes", isOK: true, detail: "MagicCardHashes.json bundled"))
        } else {
            items.append(Item(name: "Magic hashes", isOK: false, detail: "MagicCardHashes.json missing"))
        }

        return items
    }

    /// A short user-facing hint when the mode's primary on-device pipeline is
    /// disabled by missing bundled assets. Returns nil when everything needed
    /// is present (or when the mode has no bundled-asset dependency).
    static func missingAssetHint(for mode: ScanMode, bundle: Bundle = .main) -> String? {
        guard mode == .pokemon else { return nil }
        var missing: [String] = []
        if bundle.url(forResource: EmbeddingAsset.model.0, withExtension: EmbeddingAsset.model.1) == nil {
            missing.append("CardEmbeddings.mlmodelc")
        }
        if bundle.url(forResource: EmbeddingAsset.vectors.0, withExtension: EmbeddingAsset.vectors.1) == nil {
            missing.append("CardsIndexVectors.bin")
        }
        if bundle.url(forResource: EmbeddingAsset.metadata.0, withExtension: EmbeddingAsset.metadata.1) == nil {
            missing.append("CardsIndexMetadata.json")
        }
        guard !missing.isEmpty else { return nil }
        return "On-device recognition assets are missing from this build: "
            + missing.joined(separator: ", ")
            + ". Run `bash scripts/ios-assets.sh build`, then rebuild and reinstall the app."
    }
}
