// Generated by tools/pokemon/import-rarity-vectors.mjs. Do not edit.
import Foundation

struct PokemonRarityArtworkAsset: Equatable {
    let assetName: String
    let fallbackFilename: String
}

enum PokemonRarityArtworkCatalog {
    static func artwork(for rarity: String) -> PokemonRarityArtworkAsset? {
        switch rarity.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() {
        case "amazing rare":
            return PokemonRarityArtworkAsset(
                assetName: "PokemonRarityAmazingRare",
                fallbackFilename: "amazing-rare.4a876821ba5bd97b.png"
            )
        case "common":
            return PokemonRarityArtworkAsset(
                assetName: "PokemonRarityCommon",
                fallbackFilename: "common.af7e4bfde3168935.png"
            )
        case "uncommon":
            return PokemonRarityArtworkAsset(
                assetName: "PokemonRarityUncommon",
                fallbackFilename: "uncommon.713182708480c351.png"
            )
        case "rare":
            return PokemonRarityArtworkAsset(
                assetName: "PokemonRarityRare",
                fallbackFilename: "rare.df6ff2f19f0a9e6e.png"
            )
        case "holo rare":
            return PokemonRarityArtworkAsset(
                assetName: "PokemonRarityRareHolo",
                fallbackFilename: "rare-holo.df6ff2f19f0a9e6e.png"
            )
        case "rare holo":
            return PokemonRarityArtworkAsset(
                assetName: "PokemonRarityRareHolo",
                fallbackFilename: "rare-holo.df6ff2f19f0a9e6e.png"
            )
        case "shiny rare":
            return PokemonRarityArtworkAsset(
                assetName: "PokemonRarityShinyRare",
                fallbackFilename: "shiny-rare.df6ff2f19f0a9e6e.png"
            )
        case "shiny ultra rare":
            return PokemonRarityArtworkAsset(
                assetName: "PokemonRarityShinyUltraRare",
                fallbackFilename: "shiny-ultra-rare.4987458b44840d91.png"
            )
        case "ultra rare":
            return PokemonRarityArtworkAsset(
                assetName: "PokemonRarityUltraRare",
                fallbackFilename: "ultra-rare.4987458b44840d91.png"
            )
        case "promo":
            return PokemonRarityArtworkAsset(
                assetName: "PokemonRarityPromo",
                fallbackFilename: "promo.a1ea66277389c18b.png"
            )
        default:
            return nil
        }
    }
}
