// Generated by tools/pokemon/import-rarity-vectors.mjs. Do not edit.
import Foundation

struct PokemonRarityArtworkAsset: Equatable {
    let vectorFilename: String
}

enum PokemonRarityArtworkCatalog {
    static func artwork(for rarity: String) -> PokemonRarityArtworkAsset? {
        switch rarity.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() {
        case "amazing rare":
            return PokemonRarityArtworkAsset(vectorFilename: "amazing-rare.836e292370c47b8f.svg")
        case "common":
            return PokemonRarityArtworkAsset(vectorFilename: "common.2b7fcc0607f1c064.svg")
        case "uncommon":
            return PokemonRarityArtworkAsset(vectorFilename: "uncommon.371e5b180b55f4cc.svg")
        case "rare":
            return PokemonRarityArtworkAsset(vectorFilename: "rare.8a6867507251dba0.svg")
        case "holo rare":
            return PokemonRarityArtworkAsset(vectorFilename: "rare-holo.aab14d7ee57de99c.svg")
        case "rare holo":
            return PokemonRarityArtworkAsset(vectorFilename: "rare-holo.aab14d7ee57de99c.svg")
        case "shiny rare":
            return PokemonRarityArtworkAsset(vectorFilename: "shiny-rare.3c897980286fa765.svg")
        case "shiny ultra rare":
            return PokemonRarityArtworkAsset(vectorFilename: "shiny-ultra-rare.ff4a91c850802de4.svg")
        case "ultra rare":
            return PokemonRarityArtworkAsset(vectorFilename: "ultra-rare.7d1e866dc5030fa7.svg")
        case "promo":
            return PokemonRarityArtworkAsset(vectorFilename: "promo.bd2c7eb45121f553.svg")
        default:
            return nil
        }
    }
}
